Demo/Demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Home import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('account.urls')),
    url(r'^home/$',views.home)
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Demo/Home/urls.py
from django.conf.urls import url
from . import views as Home_views
app_name = "Home"

Demo/account/urls.py
from django.conf.urls import url
from . import views as account_views
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    url(r'^register/$',account_views.register,name="register"),
   # url(r'^login/$',account_views.user_login,name="login"),
    url(r'^login/$',auth_views.login,{"template_name":"account/login.html"},name="login"),
    url(r'^logout/$',auth_views.logout,{"template_name":"account/logout.html"},name="logout"),
    url(r'^password-change/$',auth_views.password_change,{"template_name":"account/password-change.html","post_change_redirect":"account:password-change-done"},name="password-change"),
    url(r'^password-change-done/$',auth_views.password_change_done,{"template_name":"account/password-change-done.html"},name="password-change-done"),
    url(r'^success/$',account_views.success,name="RegisterSuccess"),
    url(r'^failure/$',account_views.failure,name="RegisterFailure"),
    url(r'^password-reset/$',auth_views.password_reset,
        {"template_name":"account/password_reset_form.html",
          "email_template_name":"account/password_reset_email.html",
          "subject_template_name":"account/subject_template_name.txt",
         "post_reset_redirect":"/account/password-reset-done"
         },
        name="password_reset",
        ),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,
        {"template_name":"account/password_reset_confirm.html","post_reset_redirect":"/account/password-reset-complete"},
        name="password_reset_confirm"
        ),

    url(r'^password-reset-done/$',auth_views.password_reset_done,{"template_name":"account/password_reset_done.html"},name="password_reset_done"),
    url(r'^password-reset-complete/$',auth_views.password_reset_complete,{"template_name":"account/password_reset_complete.html"},name="password_reset_complete"),
    url(r'^myself/$',account_views.myself,name="myself"),
    url(r'^edit-myself/$',account_views.editmyself,name="editmyself"),
    url(r'my-image/$',account_views.my_image,name="my_image"),
]

Demo/Home/models.py
from django.db import models
import os
# Create your models here.
class ImageDisplay(models.Model):

    title = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    Img = models.ImageField(upload_to='images/Home/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    Display = models.BooleanField(default=False)
    def __str__(self):
        return self.title

Demo/account/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,unique=True)
    RealName = models.CharField(max_length=20,blank=True)
    School = models.CharField(max_length=20,blank=True)
    Class = models.CharField(max_length=20,blank=True)
    SchoolNumber = models.CharField(max_length=12)
    phone = models.CharField(max_length=11)
    photo = models.ImageField(blank=True)

    def __str__(self):
        return "user:{}",format(self.user.username)

Demo/account/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
class RegisterForm(forms.ModelForm):

    password = forms.CharField(label="Password",widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password",widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username","email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("no")
        return cd['password2']

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ("School","Class","phone","SchoolNumber","RealName","photo")

class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email",)

Demo/Home/views.py
from django.shortcuts import render
from .models import ImageDisplay
# Create your views here.

def home(request):
    Images = ImageDisplay.objects.filter(Display=True)
    return render(request,"home/Home.html",{"Images":Images})

Demo/account/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login
from .models import UserProfile
from .forms import RegisterForm,UserProfileForm,LoginForm,UserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# Create your views here.

def register(request):
    if request.method == "POST":
        user_form = RegisterForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)

        if user_form.is_valid() * userprofile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            userprofile = userprofile_form.save(commit=False)
            userprofile.user = new_user
            userprofile.save()
            return HttpResponseRedirect(reverse("account:RegisterSuccess"))
        else:
            return HttpResponseRedirect(reverse("account:RegisterFailure"))

    if request.method == "GET":
        user_form = RegisterForm()
        userprofile_form = UserProfileForm()
        return render(request,'account/register.html',{'user_form':user_form,"userprofile_form":userprofile_form})


def user_login(request):
    if request.method == "POST":
        user_form = LoginForm(request.POST)
        if user_form.is_valid():
            cd = user_form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user:
                login(request,user)
                return HttpResponse("Successful!")
            else:
                return HttpResponse("You can not login!")
        else:
            return HttpResponse("Input not valid!")

    if request.method == "GET":
        user_form = LoginForm()
        return render(request,"account/login.html",{"form":user_form})

def success(request):
    return render(request,"account/registerSuccess.html")


def failure(request):
    return render(request,"account/registerfailture.html")


@login_required(login_url='/account/login/')
def myself(request):
    user = User.objects.get(username=request.user.username)
    userprofile = UserProfile.objects.get(user=user)
    return render(request,"account/myself.html",{"user":user,"userprofile":userprofile})

@login_required(login_url='/account/login/')
def editmyself(request):
    user = User.objects.get(username=request.user.username)
    userprofile = UserProfile.objects.get(user=user)

    if request.method == "POST":
        user_form = UserForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid() * userprofile_form.is_valid():
            user_cd = user_form.cleaned_data
            userprofile_cd = userprofile_form.cleaned_data
            user.email = user_cd['email']
            userprofile.RealName = userprofile_cd['RealName']
            userprofile.School = userprofile_cd['School']
            userprofile.SchoolNumber = userprofile_cd['SchoolNumber']
            userprofile.Class = userprofile_cd['Class']
            userprofile.phone = userprofile_cd['phone']
            user.save()
            userprofile.save()
            return HttpResponseRedirect('/account/myself')

    if request.method == "GET":
        user_form = UserForm(instance=request.user)
        userprofile_form = UserProfileForm(initial={"SchoolNumber":userprofile.SchoolNumber,"School":userprofile.School,"Class":userprofile.Class,"RealName":userprofile.RealName,"phone":userprofile.phone})
        return render(request,"account/editmyself.html",{"user_form":user_form,"userprofile_form":userprofile_form})


@login_required(login_url="/account/login")
def my_image(request):
    if request.method == "POST":
        img = request.POST['img']
        userprofile = UserProfile.objects.get(user=request.user.id)
        userprofile.photo = img
        userprofile.save()
        return HttpResponse("1")
    else:
        return render(request,"account/imagecrop.html")

Demo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- swifter 插件文件-->
    <link rel="stylesheet" href="{% static 'dist/css/swiper.min.css' %}">

     <script src="{% static 'dist/js/swiper.min.js' %}"></script>
    <!-- -->
    <link rel="stylesheet" href="{% static 'css/myselfcss.css' %}">
   <!-- 新 Bootstrap4 核心 CSS 文件 -->
<!-- 新 Bootstrap4 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>

<!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
<script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>

<!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

<!-- 图标文件 -->
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">
<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %} {% endblock %}</title>
     {% block style  %} {% endblock %}
</head>
<body>
<div class="container text-center">
{% block header %}  {% endblock %}
{% block content %} {% endblock %}
{% block footer %} {% endblock %}
</div>
</body>
</html>

Demo/templates/footer.html
<footer class="text-center">
    <p>运营：华南农业大学数学与信息学院学生党务管理委员会</p>
    <p>邮箱:1066812978@qq.com</p>
    <p>微信:13326453474</p>
</footer>

Demo/templates/home/Home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block style %}
  <!-- Demo styles -->
  <style>
    html, body {
      position: relative;
      height: 100%;
    }
    body {
      background: #eee;
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 14px;
      color:#000;
      margin: 0;
      padding: 0;
    }
    .swiper-container {
      width: 100%;
      height: 100%;

    }
    .swiper-slide {
      text-align: center;
      font-size: 18px;
      background: #fff;

      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }
  </style>
    {% endblock %}
  <!-- Swiper -->
{% block header %} {% include "nav.html" %} {% endblock %}
{% block content %}

    <div class="row">
  <div class="swiper-container col-md-12" style="height: 400px;">
    <div class="swiper-wrapper">
        {% for Image in Images %}
      <div class="swiper-slide"><img src="/media/{{ Image.Img }}" width="85%" height="90%"> </div>
        {% endfor %}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>

  <!-- Swiper JS -->
  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container', {
      spaceBetween: 30,
      centeredSlides: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
  </script>
    </div>
    <nav class="border margin_0 navbar navbar-expand-md text-center">
     <ul class="navbar-nav nav-bg-color" style="width: 100%;">
     <li class="nav-item col-md-2 border"><a href="#"> 首页</a></li>
     <li class="nav-item col-md-2 border"><a href="#"> 党务工作</a></li>
     <li class="nav-item col-md-2 border"><a href="#"> 党课中心</a></li>
     <li class="nav-item col-md-2 border"><a href="#"> 党校书院</a></li>
     <li class="nav-item col-md-2 border"><a href="#"> 精品推荐</a></li>
     <li class="nav-item col-md-2 border"><a href="#"> 关于我们</a></li>
     </ul>
    </nav>
    <div class="row" style="margin:10px 0;">
    <div class="col-md-3 border text-center LoginForm">
        <h4> 登录 </h4>
       <hr>
        <div style="height: 70%; width:100%; ">
        <form action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
            <div class="input-group mb-3" style="margin:10% 4% 4%;" >
                <div class="input-group-prepend ">
                    <span class="input-group-text fa fa-male">
                    </span>
                </div>
            <input type="text" placeholder="输入用户名" id="id_username" name="username">
            </div>
           <div class="input-group mb-3" style="margin:6% 4%">
                <div class="input-group-prepend">
                    <span class="input-group-text fa fa-stack-exchange">
                    </span>
                </div>
            <input type="password" placeholder="输入密码" id="id_password" name="password">
            </div>
            <input type="submit"  class="btn btn-primary" style="width:100%;margin:6% auto;">
        </form>
             <p><a href="{% url 'account:password_reset' %}">忘记密码</a> </p>
    </div>
        </div>
    <div class="col-md-6 border Center">
      <h4> 学生党务管理委员会</h4>
        <hr>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist" style="margin:0;padding:0;">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#home">指导老师</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu1">策划部</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu2">秘书部</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu3">宣传部</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu4">培训部</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#menu5">资料部</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
      <h3>HOME</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="menu1" class="container tab-pane fade"><br>
      <h3>Menu 1</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div id="menu2" class="container tab-pane fade"><br>
      <h3>Menu 2</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
       <div id="menu3" class="container tab-pane fade"><br>
      <h3>Menu 3</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
       <div id="menu4" class="container tab-pane fade"><br>
      <h3>Menu 4</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
       <div id="menu5" class="container tab-pane fade"><br>
      <h3>Menu 5</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
  </div>
    </div>
    <div class="col-md-3 border Right">
        <h4> 网站介绍 </h4>
        <hr>
    </div>
    </div>
    <div class="row border" style="margin:0;">
    <div class="col-md-4 border Area">
      <h4> 党务工作 </h4>
        <hr>

    </div>
     <div class="col-md-8 border Area">
      <h4> 最近更新 </h4>
        <hr>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist" style="margin:0;padding:0;">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#News">时事</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#Video">党课视频</a>
    </li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="News" class="container tab-pane active"><br>
      <h3>时事</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="Video" class="container tab-pane fade"><br>
      <h3>党课视频</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
      </div>
    </div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}
{% endblock %}

Demo/templates/nav.html
{% load staticfiles %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark d-flex flex-row bg-secondary" style="padding:0;">
    <div class="nav-left p-2" style="width:20%;">
    <a class="navbar-brand" href="#">
        <img class="img-fluid rounded-circle" src="{% static 'Image/ScauLogo.jpg' %}" alt="logo" style="width: 80px; height: 50px;">
         <img class="img-fluid rounded-circle" src="{% static 'Image/DangLogo.png' %}" alt="logo" style="width: 75px; height: 50px;">
    </a>
       </div>
    <div class="nav-right" style="width:75%;">
    <ul class="navbar-nav p-2 d-flex flex-row-reverse">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown p-2">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">{{ user.username}}</button>
            <div class="dropdown-menu">

                    <a class="dropdown-item" href="{% url 'account:password-change' %}">修改密码</a>
                    <a class="dropdown-item" href="{%  url 'account:logout' %}">退出登陆</a>
                    <a class="dropdown-item" href="{% url 'account:myself' %}">个人信息</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item p-2">
           <button type="button" class="btn btn-primary"><a href="{% url 'account:login' %}" style="color:white;">Login </a></button>
        </li>
        <li class="nav-item p-2">
            <button type="button" class="btn btn-primary"><a href="{% url 'account:register' %}" style="color:white;">register</a></button>
        </li>
        {% endif %}
    </ul>
        </div>
</nav>